[package]
name = "ppdrive-video-compression-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ppdrive-video-compression = { path = ".." }

[[bin]]
name = "fuzz_transcode"
path = "fuzz_targets/fuzz_transcode.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
